version: '3.7'

services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  kibana:
    build: ./kibana
    container_name: kibana
    ports:
      - 5601:5601
